<script setup>
import { router } from '@inertiajs/vue3';
import { ref } from 'vue';
const props = defineProps({ activePortfolio: Object, portfolios: Array, batches: Array });
const preview = ref(null); const error = ref(null); const file = ref(null); const loading = ref(false);
function choosePortfolio(event) { router.post('/portfolio/active', { portfolioId: Number(event.target.value) }, { onSuccess: () => router.reload() }); }
function upload() { if (!file.value) return; loading.value = true; error.value = null; const data = new FormData(); data.append('workbook', file.value); fetch('/portfolio/imports/xtb', { method: 'POST', body: data, headers: { Accept: 'application/json', 'X-Requested-With': 'XMLHttpRequest' } }).then(async r => { const body = await r.json(); if (!r.ok) throw body; preview.value = body; }).catch(e => error.value = e.errors?.workbook?.[0] || e.message || 'Upload failed.').finally(() => loading.value = false); }
function confirm() { if (!preview.value) return; loading.value = true; fetch(`/portfolio/imports/xtb/${preview.value.importId}/confirm`, { method: 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json', 'X-Requested-With': 'XMLHttpRequest' }, body: JSON.stringify({ mappings: {} }) }).then(async r => { const body = await r.json(); if (!r.ok) throw body; preview.value = null; router.reload(); }).catch(e => error.value = e.errors?.workbook?.[0] || 'Import confirmation failed.').finally(() => loading.value = false); }
function batchAction(id, action) { fetch(`/portfolio/import-batches/${id}${action === 'delete' ? '' : '/reprocess'}`, { method: action === 'delete' ? 'DELETE' : 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json', 'X-Requested-With': 'XMLHttpRequest' }, body: action === 'delete' ? null : JSON.stringify({ mappings: {} }) }).then(() => router.reload()); }
</script>
<template>
  <main aria-labelledby="xtb-import-heading"><nav aria-label="Application"><a href="/portfolio/imports/xtb">Imports</a> <a href="/portfolio/valuation?date=2026-01-02">Valuation</a><form action="/logout" method="post"><button>Log out</button></form><label>Active portfolio <select :value="activePortfolio.id" @change="choosePortfolio"><option v-for="portfolio in portfolios" :key="portfolio.id" :value="portfolio.id">{{ portfolio.broker }} — {{ portfolio.accountReference }}</option></select></label></nav><h1 id="xtb-import-heading">XTB import</h1><input type="file" accept=".xlsx" @change="file = $event.target.files[0]"><button :disabled="loading || !file" @click="upload">Preview import</button><p v-if="error" role="alert">{{ error }}</p><section v-if="preview" aria-label="Import preview"><h2>Parse-only preview</h2><p>Valid: {{ preview.summary.valid }}, pending: {{ preview.summary.pending }}, rejected: {{ preview.summary.rejected }}</p><button :disabled="loading" @click="confirm">Confirm import</button></section><section><h2>Import batches</h2><ul><li v-for="batch in batches" :key="batch.id">#{{ batch.id }} — {{ batch.status }} <button @click="batchAction(batch.id, 'reprocess')">Reprocess</button> <button @click="batchAction(batch.id, 'delete')">Destroy</button></li></ul></section></main>
</template>
